<a href="https://colab.research.google.com/github/Cxris2145/MineriaDatos2026/blob/main/ExportacionesChile2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.kaggle.com/datasets/michallublin/chile-export-products-20172021

https://github.com/UXDynamicSolution/MineriaDatosDuocPAO/blob/main/eda_ejercicio.ipynb

In [13]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [2]:
# Para ver todas las columnas sin cortes
pd.set_option('display.max_columns', None)

# Para ver todas las filas (cuidado si el dataset es muy grande)
pd.set_option('display.max_rows', None)

In [3]:
import pandas as pd

# Carga de datos
df = pd.read_csv("ChileExport.csv", sep=';')
df.head()

,Country,1 category,2 category,Product,Year,Income in USD
0,China,Minero,Minería,Minerales de cobre y sus concentrados,2017,6470444174
1,China,Minero,Minería,Cobre,2017,7604230274
2,China,Minero,Minería,Minerales de hierro y sus concentrados,2017,"616711446,1"
3,China,Minero,Minería,Litio,2017,234218255
4,China,Minero,Minería,Minerales de molibdeno y sus concentrados,2017,"37490057,93"

In [4]:
df_anio = df["Year"].describe()
print(df_anio)

count    21385.000000
mean      2019.000000
std          1.414247
min       2017.000000
25%       2018.000000
50%       2019.000000
75%       2020.000000
max       2021.000000
Name: Year, dtype: float64

In [5]:
# Cuenta en cuántas filas (registros de exportación) aparece cada país de destino.
# Chile tuvo más transacciones o diversidad de productos exportados entre 2017 y 2021.

df_country = df["Country"].value_counts()
print(df_country)

Country
Estados Unidos de América                              355
China                                                  350
Japón                                                  335
Perú                                                   335
Brasil                                                 330
Canadá                                                 330
España                                                 330
Alemania                                               315
Colombia                                               315
México                                                 310
Holanda                                                305
Corea del Sur                                          305
Italia                                                 300
Reino Unido                                            295
Argentina                                              295
Bélgica                                                280
Ecuador                                                275
Uruguay                                                275
Hong Kong (Región administrativa especial de China)    270
Australia                                              265
Costa Rica                                             265
Bolivia                                                260
Francia                                                260
Panamá                                                 255
Taiwán (Formosa)                                       250
Paraguay                                               240
India                                                  235
Rusia                                                  230
República Dominicana                                   230
Dinamarca                                              225
Tailandia                                              225
Singapur                                               215
Malasia                                                215
Suecia                                                 205
Emiratos Árabes Unidos                                 205
Guatemala                                              205
Vietnam                                                205
Polonia                                                200
El Salvador                                            200
Portugal                                               200
Nueva Zelandia                                         200
Sudáfrica                                              195
Arabia Saudita                                         190
Suiza                                                  190
Venezuela                                              190
Cuba                                                   190
Turquía                                                185
Filipinas                                              185
Puerto Rico                                            180
Indonesia                                              180
Otros                                                  170
Honduras                                               170
Territorio Británico en América                        165
Nicaragua                                              160
Austria                                                160
Grecia                                                 160
Lituania                                               155
Finlandia                                              155
Noruega                                                150
Irlanda                                                145
Israel                                                 140
Trinidad y Tobago                                      135
Rumania                                                135
Ucrania                                                130
República Checa                                        130
Jamaica                                                130
Chipre                                                 120
Egipto                                                 115
Kuwait                                                 110
Jordania                                               110
Bulgaria                                               110
Guyana                                                 110
Libano                                                 105
Letonia                                                105
Territorio Francés en América                           95
Sri Lanka                                               95
Qatar                                                   95
Bahrein                                                 95
Antillas Neerlandesas                                   90
Islandia                                                90
Polinesia Francesa                                      90
Georgia                                                 85
Hungría                                                 85
Belarus                                                 85
Omán                                                    85
Haití                                                   85
Cambodia                                                80
Kenia                                                   80
Estonia                                                 80
Marruecos                                               75
Bangladesh                                              75
Pakistán                                                75
Territorio Holandés en América                          75
Eslovenia                                               75
Kazajstán                                               75
Argelia                                                 70
Ghana                                                   70
Nigeria                                                 70
Aruba                                                   70
Territorio Francés en Oceanía y el Pacífico             70
Martinica                                               70
Nueva Caledonia                                         70
Bahamas                                                 65
Belice                                                  65
Croacia                                                 65
Malta                                                   65
Mongolia                                                60
Costa de Marfil                                         60
Luxemburgo                                              60
Tunez                                                   60
República de Serbia                                     55
Angola                                                  55
Surinam                                                 55
Barbados                                                55
Fiji                                                    50
Dominica                                                50
Senegal                                                 50
Togo                                                    50
Territorio Francés en África                            50
Liberia                                                 50
Myanmar (ex Birmania)                                   50
Antigua y Barbuda                                       50
Azerbaiyan                                              45
República Eslovaca                                      45
Moldova                                                 45
Gabón                                                   45
Iraq                                                    45
Brunei                                                  40
Laos                                                    40
Congo                                                   40
Macao                                                   40
Mozambique                                              40
Islas Caymán                                            40
Guinea Ecuatorial                                       40
San Vicente y las Granadinas                            40
Albania                                                 40
Mauricio                                                40
Santa Lucía (Islas  Occidentales)                       40
Namibia                                                 35
Benin                                                   35
Tanzania                                                35
Camerún                                                 35
Islas Vírgenes Británicas                               35
Turcas y Caicos                                         35
Bosnia y Herzegovina                                    35
Kirgistán                                               35
Mauritania                                              35
Libia                                                   35
Guam                                                    35
Granada                                                 35
Bermudas                                                35
San Marino                                              30
Saint Kitts & Nevis                                     30
Guinea                                                  30
Armenia                                                 30
Nepal                                                   30
Micronesia                                              30
Sierra Leona                                            30
Uzbekistán                                              30
Islas Vírgenes (EEUU)                                   25
Niger                                                   25
Zambia                                                  25
Etiopía                                                 25
Isla Maldivas                                           25
Irán                                                    20
Burkina Faso                                            20
República Democrática del Congo                         20
Montenegro                                              20
Macedonia                                               20
Anguila                                                 20
Uganda                                                  20
Seychelles                                              20
Gibraltar                                               20
Cabo Verde                                              20
Samoa Occidental                                        20
Rwanda                                                  15
Swazilandia                                             15
Mali                                                    15
Isla Tonga                                              15
Siria                                                   15
Papua Nueva Guinea                                      15
Islas Marshall                                          15
Djibouti                                                15
Vanuatu                                                 15
Islas Cook                                              15
Liechtenstein                                           15
Chad                                                    15
República Centroafricana                                15
Territorio de Dinamarca en América                      15
Islas Marianas del Norte                                10
Tuvalu                                                  10
Andorra                                                 10
Zimbabwe                                                10
Afghanistán                                             10
Comoras                                                 10
Sudán                                                   10
Mónaco                                                  10
Botswana                                                10
Kiribati                                                10
Territorio Portugués en Asia                            10
Gambia                                                  10
Malawi                                                  10
Territorio Británico en Oceanía y el Pacífico           10
Tadjikistán                                              5
Somalia                                                  5
Guernsey                                                 5
Madagascar                                               5
Palestina                                                5
Eritrea                                                  5
Guinea - Bissau                                          5
Islas Salomon                                            5
Niue                                                     5
Monserrat                                                5
Turkmenistan                                             5
Jersey                                                   5
Ciskey                                                   5
Sao Tome y Principe                                      5
Territorio Norteamericano en Oceanía y el Pacífico       5
Nauru                                                    5
Burundi                                                  5
Groenlandia                                              5
República de Yemen                                       5
Timor Oriental                                           5
Name: count, dtype: int64

In [6]:
df_country = df["1 category"].value_counts()
print(df_country)

1 category
No minero      19505
Minero          1865
(en blanco)       15
Name: count, dtype: int64

In [7]:
df_country = df["2 category"].value_counts()
print(df_country)

2 category
Frutas y frutos                                     5440
Otros alimentos                                     3345
Productos del mar                                   2855
Forestales y sus derivados                          2150
Otros productos relevantes                          2040
Minería                                             1865
Vitivinícola                                        1815
Resto No minería                                    1060
Exportación de servicios calificados por Aduanas     800
(en blanco)                                           15
Name: count, dtype: int64

In [8]:
df_country = df["Product"].value_counts()
print(df_country)

Product
Resto No minería                                    1060
Vinos                                                840
Exportación de servicios calificados por Aduanas     800
Madera y sus manufacturas                            645
Resto Forestales y sus derivados                     620
Papel y cartón y sus manufacturas                    605
Uvas                                                 600
Conservas y preparaciones de pescados y mariscos     590
Resto Otros alimentos                                590
Vinos espumosos                                      580
Manzanas                                             500
Ciruelas                                             490
Salmones y truchas                                   470
Nueces de nogal                                      460
Medicamentos                                         445
Kiwis                                                410
Resto Frutas y frutos                                395
Mostos de uva                                        395
Resto Productos del mar                              385
Resto Minería                                        380
Hortalizas y tubérculos                              350
Arándanos                                            345
Abonos                                               345
Jugos de frutas, frutos y hortalizas                 340
Cerezas                                              340
Peras                                                340
Jureles                                              315
Tomates preprarados o conservados                    310
Semillas para siembra                                305
Celulosa                                             280
Nitratos de potasio                                  275
Moluscos                                             265
Cobre                                                265
Duraznos y nectarinas                                265
Frambuesas y moras                                   255
Carnes de ave                                        245
Neumáticos                                           240
Aceites de oliva                                     235
Grasas y aceites de pescado                          230
Carnes de porcino                                    225
Leche y otros productos lácteos                      220
Frutillas                                            215
Bacalaos                                             200
Granos de avena                                      200
Cecinas y embutidos                                  185
Paltas                                               180
Algas                                                175
Minerales de cobre y sus concentrados                175
Minerales de molibdeno y sus concentrados            175
Naranjas                                             170
Miel                                                 165
Ferroaleaciones                                      160
Harinas de pescado                                   160
Yodo                                                 155
Mandarinas y clementinas                             155
Limones                                              155
Litio                                                145
Carnes de otras especies                             140
Carnes de bovino                                     140
Sal gema, sal de salinas y sal marina                140
Minerales de hierro y sus concentrados               115
Plata                                                110
Alambres de cobre                                    110
Avellanas                                            100
Óxidos e hidróxidos de molibdeno                      85
Metanol                                               75
Maquis                                                65
Erizos                                                65
Oro                                                   65
Minerales de oro y sus concentrados                   60
Minerales de cinc y sus concentrados                  55
Minerales de plomo y sus concentrados                 25
(en blanco)                                           15
Name: count, dtype: int64

In [9]:
df.tail()

,Country,1 category,2 category,Product,Year,Income in USD
21380,Gambia,No minero,Exportación de servicios calificados por Aduanas,Exportación de servicios calificados por Aduanas,2021,0
21381,Gambia,No minero,Resto No minería,Resto No minería,2021,0
21382,Groenlandia,No minero,Resto No minería,Resto No minería,2021,0
21383,República de Yemen,No minero,Resto No minería,Resto No minería,2021,0
21384,Timor Oriental,No minero,Resto No minería,Resto No minería,2021,0

In [11]:
df.shape

(21385, 6)

In [15]:
df.dtypes

Country          object
1 category       object
2 category       object
Product          object
Year              int64
Income in USD    object
dtype: object

In [16]:
df.isnull().sum()

Country          0
1 category       0
2 category       0
Product          0
Year             0
Income in USD    0
dtype: int64

In [18]:
df.columns

Index(['Country', '1 category', '2 category', 'Product', 'Year',
       'Income in USD'],
      dtype='object')